apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        ports:
          - containerPort: 2368 

---

apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 2368 
    targetPort: 2368
  type: LoadBalancer 
    


